### ISSUE TITLE
`step.clone-path` does not match current Bitbucket behavior

### ISSUE THREAD

**Issue by addisonklinke** [ktomk/pipelines#12] opened 2021-11-01 14:33 UTC
The default config parameter for `step.clone-path` mentioned in this [doc](https://github.com/ktomk/pipelines/blob/6703f1ddb0ba397c1e0189fe8d25aa572ed01705/doc/CONFIGURATION-PARAMETERS.md) is `/app` whereas when a pipeline runs in Bitbucket (as of 10/29/21) the mount point is `/build`. This discrepancy should be resolved so that users do not have to manually configure this option to mimic the full Bitbucket behavior

**Comment by ktomk** [comment] 2021-11-01 16:23
The recommendation I know is to not use the path but instead rely on `$BITBUCKET_CLONE_DIR` (which should work). That is what Bitbucket itself also suggests you should do, so to mimic the full Bitbucket behavior please consider it.

Regardless, this `/build` path is news to me, so far I had `/opt/atlassian/pipelines/agent/build` noted, will check it.

Finally, I also see no problem to change the default from `/app` to `/build`. It is similarly short and by the name a better fit for pipelines. I'll take a look.

**Comment by ktomk** [comment] 2021-11-05 14:51
Okay let's put a TM sign on "should work". Turned out it didn't when the config parameter was used as intended.

I'll file a fix for this. As well for support to use `/opt/atlassian/pipelines/agent/build` as the setting (which already works, but not stable).

Because of the fixes I plan to keep the current default for now as I don't want to introduce too many changes at once.

Could you tell me if you did run into an actual issue and if so, share it here? I'd like to better understand your requirement.

**Comment by ktomk** [comment] 2021-11-07 23:38
Version 0.0.58 has just been released with fixes regarding the `step.clone-path` configuration parameter.

**Comment by ktomk** [comment] 2021-12-06 23:49
@addisonklinke Thanks for taking the time raising this issue. In regard of `$BITBUCKET_CLONE_DIR` and the applied fixes in 0.0.58 some feedback would be helpful to decide on the next steps.

If I understand your topmost request right, the change request is to change the `step.clone-path`s' default value from `/app` to `/opt/atlassian/pipelines/agent/build` (the default path, you originally wrote `/build` but as written earlier I'm unable to see `/build` as default).

As I don't know if it is still a requirement for you (e.g. `$BITBUCKET_CLONE_DIR` for some reason is not useful or still broken), I'll close this issue for now. But please feel free to re-open it and/or leave further comments.

**Closed as completed by ktomk** 2021-12-06 23:49 UTC
Labels: invalid
